In [1]:
# Import libraries
import pandas as pd
import numpy as np

In [2]:
# Import Raw of Dataset
df = pd.read_csv("India Agriculture Crop Production.csv")
df.head(5)

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield
0,Andaman and Nicobar Islands,NICOBARS,Arecanut,2001-02,Kharif,1254.0,Hectare,2061.0,Tonnes,1.643541
1,Andaman and Nicobar Islands,NICOBARS,Arecanut,2002-03,Whole Year,1258.0,Hectare,2083.0,Tonnes,1.655803
2,Andaman and Nicobar Islands,NICOBARS,Arecanut,2003-04,Whole Year,1261.0,Hectare,1525.0,Tonnes,1.209358
3,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,Arecanut,2001-02,Kharif,3100.0,Hectare,5239.0,Tonnes,1.690000
4,Andaman and Nicobar Islands,SOUTH ANDAMANS,Arecanut,2002-03,Whole Year,3105.0,Hectare,5267.0,Tonnes,1.696296

In [3]:
# Check the info of each column (total row, column, null values)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345407 entries, 0 to 345406
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   State             345407 non-null  object
 1   District          345407 non-null  object
 2   Crop              345375 non-null  object
 3   Year              345407 non-null  object
 4   Season            345406 non-null  object
 5   Area              345374 non-null  float64
 6   Area Units        345407 non-null  object
 7   Production        340414 non-null  float64
 8   Production Units  345407 non-null  object
 9   Yield             345374 non-null  float64
dtypes: float64(3), object(7)
memory usage: 26.4+ MB

In [4]:
# Check null values in the data
df.isna().sum()

State                  0
District               0
Crop                  32
Year                   0
Season                 1
Area                  33
Area Units             0
Production          4993
Production Units       0
Yield                 33
dtype: int64

In [5]:
print("Total row BEFORE droping null values:", df.shape[0])

# Note
"""
If the Area is nothing (null), it won't producting any crop
So the rows with null Area should be removed
"""

df = df.dropna(subset=['Area'])
print("Total row AFTER droping null values:", df.shape[0])

Total row BEFORE droping null values: 345407
Total row AFTER droping null values: 345374

In [6]:
# Recheck null values after drop 1 column
df.isna().sum()

State                  0
District               0
Crop                   0
Year                   0
Season                 0
Area                   0
Area Units             0
Production          4960
Production Units       0
Yield                  0
dtype: int64

In [18]:
# Note
null_prod = df['Production'].isna().sum()
print(f"""
      There are no null values in all column, except 'Production'.
      There are {null_prod} null values, that means no crop is produced.
      You can replace it with 0 value, so that the data is completely clean from null values.
      But you can ignore it (this will have no effect).
      """)

# Replace null values of 'Production' to be 0 value
df['Production'] = df['Production'].fillna(0)

      There are no null values in all column, except 'Production'.
      There are 0 null values, that means no crop is produced.
      You can replace it with 0 value, so that the data is completely clean from null values.
      But you can ignore it (this will have no effect).

In [19]:
# Recheck null values (final)
df.isna().sum()

State               0
District            0
Crop                0
Year                0
Season              0
Area                0
Area Units          0
Production          0
Production Units    0
Yield               0
dtype: int64

In [20]:
# Check duplicate values
duplicate = df.duplicated().sum()
if duplicate == 0:
    print("The duplicate values is 0, nothing to remove")
else:
    print(f"The duplicate values is {duplicate}, go remove it")

The duplicate values is 0, nothing to remove

In [21]:
# Check all of the Year is complete
df['Year'].unique()

array(['2001-02', '2002-03', '2003-04', '2004-05', '2005-06', '2006-07',
       '2007-08', '2008-09', '2009-10', '2010-11', '2011-12', '2012-13',
       '2013-14', '2014-15', '2015-16', '2016-17', '2017-18', '2018-19',
       '2019-20', '2020-21', '2000-01', '1997-98', '1998-99', '1999-00'],
      dtype=object)

In [22]:
# Remove 3 back characters of 'Year'
df['Year'] = df['Year'].str.slice(0, -3)

In [23]:
# Changing all values of 'District' to Title Case
df['District'] = df['District'].str.title()

In [24]:
# Round down all values of 'Yield' to 2 digits after decimal
df['Yield'] = df['Yield'].round(2)

In [25]:
# Convert all unit of the 'Production' values to Tonne
"""
1 Tonne = 1 Tonne
1 Nut = 0.0001 Tonne
1 Bale = 0.22 Tonne
"""

df['Production in Tonnes'] = df.apply(lambda row:
                                        row['Production'] if row['Production Units'] == 'Tonnes'
                                        else row['Production'] * 0.0001 if row['Production Units'] == 'Nuts'
                                        else row['Production'] * 0.22 if row['Production Units'] == 'Bales'
                                        else None, axis=1)

In [26]:
# Assign the clean data into a new variable
df_clean = df
df_clean

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield,Production in Tonnes
0,Andaman and Nicobar Islands,Nicobars,Arecanut,2001,Kharif,1254.0,Hectare,2061.0,Tonnes,1.64,2061.0
1,Andaman and Nicobar Islands,Nicobars,Arecanut,2002,Whole Year,1258.0,Hectare,2083.0,Tonnes,1.66,2083.0
2,Andaman and Nicobar Islands,Nicobars,Arecanut,2003,Whole Year,1261.0,Hectare,1525.0,Tonnes,1.21,1525.0
3,Andaman and Nicobar Islands,North And Middle Andaman,Arecanut,2001,Kharif,3100.0,Hectare,5239.0,Tonnes,1.69,5239.0
4,Andaman and Nicobar Islands,South Andamans,Arecanut,2002,Whole Year,3105.0,Hectare,5267.0,Tonnes,1.70,5267.0
...,...,...,...,...,...,...,...,...,...,...,...
345370,West Bengal,Purba Bardhaman,Wheat,2000,Rabi,6310.0,Hectare,15280.0,Tonnes,2.42,15280.0
345371,West Bengal,Purulia,Wheat,1997,Rabi,1895.0,Hectare,2760.0,Tonnes,1.46,2760.0
345372,West Bengal,Purulia,Wheat,1998,Rabi,3736.0,Hectare,5530.0,Tonnes,1.48,5530.0
345373,West Bengal,Purulia,Wheat,1999,Rabi,2752.0,Hectare,6928.0,Tonnes,2.52,6928.0
345374,West Bengal,Purulia,Wheat,2000,Rabi,2979.0,Hectare,7430.0,Tonnes,2.49,7430.0

In [16]:
# Save the clean data to Excel
df.to_excel("clean_Dataset.xlsx", index = False)

### And Done. The Dataset is Ready to use:)